### ISSUE TITLE
Issue during the execution of program

### ISSUE THREAD

**Issue by raghuveersinghdhaka** [raj713335/Clustering_Networks#1]
Hi, I am executing the code provided by you on the github. The problem I faced during the execution of the code is that it asks me to **ENTER THE TIME INTERVAL IN UNITS**. I searched the pdf provided by you but unable to find the correct value for this. Kindly help in providing the correct value for this so that i can get the correct results.

I shall be very thankful if you provide me with the correct value.

**Comment by raj713335** [comment]
Enter any time Interval for example 10

**Comment by raghuveersinghdhaka** [comment]
> Enter any time Interval for example 10

Can you please provide the importance that why we are entering the time interval and 10 is what seconds or minutes or hours.

**Comment by raj713335** [comment]
It's just an imaginary UNIT, it can be anything according to user needs. 

It denotes the time, by which our nodes, are getting dropped, in our area.
